version: '3.8'

services:
  backend:
    build: ./backend
    container_name: cave-explorer-backend
    ports:
      - "8000:8000"
    environment:
      - DEV_MODE=true

  frontend:
    build: ./frontend  
    container_name: cave-explorer-frontend
    ports:
      - "3000:3000"
    environment:
      - VITE_API_URL=http://localhost:8000
    depends_on:
      - backend